### ISSUE TITLE
ImportError: cannot import name 'tracing_enabled' from 'langchain_core.tracers.context'

### ISSUE THREAD

**Issue by s1lviu** [gpt-engineer-org/gpt-engineer#953]
Did a fresh installation on my M1 MBP and failed as below:

```
silviu@Silvius-MBP IdeaProjects % gpte project
Traceback (most recent call last):
  File "/opt/homebrew/bin/gpte", line 5, in <module>
    from gpt_engineer.applications.cli.main import app
  File "/opt/homebrew/lib/python3.11/site-packages/gpt_engineer/applications/cli/main.py", line 38, in <module>
    from gpt_engineer.applications.cli.cli_agent import CliAgent
  File "/opt/homebrew/lib/python3.11/site-packages/gpt_engineer/applications/cli/cli_agent.py", line 4, in <module>
    from gpt_engineer.core.ai import AI
  File "/opt/homebrew/lib/python3.11/site-packages/gpt_engineer/core/ai.py", line 12, in <module>
    from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/callbacks/__init__.py", line 45, in <module>
    from langchain_core.tracers.context import (
ImportError: cannot import name 'tracing_enabled' from 'langchain_core.tracers.context' (/opt/homebrew/lib/python3.11/site-packages/langchain_core/tracers/context.py)
```

**Comment by s1lviu** [comment]
So it seems https://github.com/langchain-ai/langchain/issues/15491

**Comment by infinitelos** [comment]
Possible solution, as suggested in above is to lock the version of core:
langchain-core==0.1.4

To fix, I changed my pyproject.toml to:
langchain = ">0.0.335, <0.1.5"
langchain-core = ">0.0.335, <0.1.5"

**Comment by aguara-guazu** [comment]
this bug was introduced in langchain 0.0349, 0.0.348 works just fine

**Comment by collinsomniac** [comment]
Just encountered this issue and resolved it with @greenpau 's recommended fix. The key was to specify the exact versions in the `requirements.txt` file prior to installing `gpt-researcher`. Here are the steps I followed for a smooth setup:

## Resolved Issue: Specifying Versions in `requirements.txt` for GPT-Researcher Installation
### Steps for Setting up GPTResearcher

1. **Prepare a Fresh Folder for GPTResearcher**
   - _Optional_: Create a conda environment for isolation of dependency variables (`conda create --name gptresearcher`). This helps in minimizing any interference from other installations.
   
2. **Navigate to the Folder in Command Prompt**
   - Use the command `cd /D D:/YourGPTResearcherFolder/itwillgohereas(gpt-researcher)` to change your directory to the folder where you plan to clone `gpt-researcher`.

3. **Clone the GPT-Researcher Repository**
   - Execute `git clone https://github.com/assafelovic/gpt-researcher.git` in Command Prompt to clone the repository into your folder.

4. **Change Directory to the Cloned Repository**
   - Once cloned, switch to the directory using `cd gpt-researcher`.

5. **Edit `requirements.txt` File**
   - Open `D:/YourGPTResearcherFolder/gpt-researcher/requirements.txt` in a text editor.
   - Modify the file to include the following versions:
     ```
     langchain==0.0.350
     langchain-community==0.0.2
     langchain-core==0.1.0
     ```
   - In my experience, `langchain` was already there, but `community` and `core` were missing.

6. **Install the Requirements**
   - Run `pip install -r requirements.txt` in Command Prompt to install the specified dependencies.

**Note**: After these steps, ensure that your `.env` keys (e.g., `OPENAI_API_KEY` and `TAVILY_API_KEY`) are set correctly. In my case, it worked well with the default settings.

This process resolved the issue for me, hope it helps others!

**Comment by ATheorell** [comment]
Now that you have been reading up on this and playing  around @greenpau, @collinsomniac , @s1lviu @infinitelos @aguara-guazu 
Are there any drawbacks with raising the langchain requirement in gpt-engineer to:
langchain = ">=0.0.350"
Are there any known compatibility losses associated with this? I suppose that may (partly?) solve this

**Comment by s1lviu** [comment]
@ATheorell for people like me who used the production installation method I think this is still an issue?

**Comment by ATheorell** [comment]
@s1lviu 
I'm not sure what you mean. We haven't done anything to fix this, so unless you are using gpt-researcher and the instructions by  @collinsomniac

**Comment by s1lviu** [comment]
I've installed the software using `python -m pip install gpt-engineer` and was not sure requirements.txt can be provided with this method, as I'm not so familiar with python.

But the issue seems to be fixed now. I have run `pip install --upgrade gpt_engineer langchain_core` and it disappeared.

Thanks!
